# Generated by Django 2.2.6 on 2023-02-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Изменить фото профиля', null=True, upload_to='users_images', verbose_name='Фото профиля'),
        ),
    ]
