# Generated by Django 3.2 on 2023-04-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230416_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
